services:
  elasticsearch:
    image: dockerhub.greensight.ru/services/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - "read_only_allow_delete=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - "elastic-data:/usr/share/elasticsearch/data:rw"
    ports:
      - "9200:9200"

  kibana:
    image: dockerhub.greensight.ru/services/kibana:8.7.0
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "XPACK_GRAPH_ENABLED=false"
      - "XPACK_ML_ENABLED=false"
      - "XPACK_REPORTING_ENABLED=false"
      - "XPACK_WATCHER_ENABLED=false"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

volumes:
  elastic-data:
    driver: local
